### ISSUE TITLE
Fix authentication with Github

### ISSUE THREAD

**Issue by gonzalog** [uqbar-project/mumuki-platform#76] opened 2015-01-14 19:12 UTC
After clicking on the 'Sign in with Github' link I get this page:
![screenshot from 2015-01-14 16 04 31](https://cloud.githubusercontent.com/assets/4143064/5745509/205188b2-9c08-11e4-8963-76985752eace.png)

**Comment by aguspina** [comment] 2015-01-14 19:58
This bug was fixed some days ago, please try again and let us know if it still happening.

**Comment by MiguelArrondo** [comment] 2015-01-15 04:17
Hi, I'm getting the exact same issue when trying to sign in with Github.

**Comment by aguspina** [comment] 2015-01-15 04:19
Are you trying in mumuki.io or mumuki.herokuapp.com? ?

**Comment by MiguelArrondo** [comment] 2015-01-15 04:22
I was trying on mumuki.herokuapp.com, I just tried mumuki.io and it worked just fine!

**Comment by flbulgarelli** [comment] 2015-01-23 03:38
Closing since it couldn't be reproduced

**Closed by flbulgarelli** 2015-01-23 03:38 UTC
